### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by giannoma** [edpclau/circadian-dynamics#12]
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/65670450/88563765-f7d49f80-cff7-11ea-908a-3076bf3bf746.png">

Please see image above

**Comment by edpclau** [comment]
Fixed. The function "read_trikinetics_folder" was misspelled in the NAMESPACE folder. Therefore, when installing, the pkg couldn't find the function.
