### ISSUE TITLE
Export not working if only one individual is selected in the trikinectics workflow

### ISSUE THREAD

**Issue by giannoma** [edpclau/circadian-dynamics#14]
export_all(raw_data = dplyr::select(monitor_downsampled, datetime, `IND 10`),
           processed_data = list(monitor_processed$mean, monitor_processed$`IND 10`),
           rythm_analysis_data = monitor_analysis,
           autocorrelation = TRUE,
           new_dir_name = "2020_07_30_ Mon40_10")

![image](https://user-images.githubusercontent.com/65670450/88937263-8855ee80-d249-11ea-950d-7812ce88579d.png)

**Comment by edpclau** [comment]
The export all function was assuming there would always be a "mean" individual. Now, it'll carry out a test instead of assuming existence.

**Comment by giannoma** [comment]
New error while it runs now it does not output the individual summary graph or the window plots.

**Comment by edpclau** [comment]
Try removing the "mean" individual since we're not using it.

export_all(raw_data = dplyr::select(monitor_downsampled, datetime, IND 10),
processed_data = list(monitor_processed$IND 10),
rythm_analysis_data = monitor_analysis,
autocorrelation = TRUE,
new_dir_name = "2020_07_30_ Mon40_10")

**Comment by edpclau** [comment]
Remember to remove the "mean" IND from the monitor_analysis

**Comment by giannoma** [comment]
Removing the mean still results in no individual files.

**Comment by giannoma** [comment]
Everything seems to run but the output files for the individuals are not made. here are the functions I am running. 


monitor_processed <- multivariate_process_timeseries(
  df = monitor_downsampled,
  sampling_rate = '30 min',
  window_size_in_days =7,
  window_step_in_days = 1, 
  detrend_data = TRUE,
  butterworth = TRUE,
  f_low=1/4,
  f_high=0,
  plot = TRUE
  )


monitor_analysis <- multivariate_rythm_analysis(
  list(monitor_processed$`IND 10`, monitor_processed$`IND 27`),
  sampling_rate = "30 min",
  alpha=0.000000001,
  autocorrelation = TRUE,
  lomb_scargle = TRUE,
    from = 16, to = 32,
  ofac =60)
export_all(raw_data = dplyr::select(monitor_downsampled, datetime, `IND 10`,`IND 27`),
           processed_data = list(monitor_processed$`IND 10`,monitor_processed$`IND 27`),
           rythm_analysis_data = monitor_analysis,
           autocorrelation = TRUE,
           new_dir_name = "2020_07_31_Mon40_10")
<img width="515" alt="image" src="https://user-images.githubusercontent.com/65670450/89076793-93427900-d346-11ea-8e76-ba9dcf29320d.png">


also, I tried to run. export_plots_multivariate. this only made an empty folder called analysis.

export_plots_multivariate(processed_data =list(monitor_processed$`IND 10`,monitor_processed$`IND 12`), rythm_analysis_data = monitor_analysis,
autocorrelation = TRUE, lomb_scargle = TRUE, cosinor_fit = c("lomb_scargle", "autocorrelation"),
dir_choose_gui = TRUE, new_dir_name = "analysis")

**Comment by edpclau** [comment]
Fixed.

`
monitor <- read_trikinetics()
ld_data <- monitor[1:2]
monitor_downsampled <- downsample_time_series(monitor[,c(1,3)], amount = 30, units = "minutes", method = "mean")

monitor_processed <- multivariate_process_timeseries(
  monitor_downsampled,
  sampling_rate = "30 min",
  butterworth = TRUE,
  detrend_data = TRUE,
  f_low = 1/2,
  f_high = 0
)



monitor_analysis <- multivariate_rythm_analysis(
  monitor_processed,
  sampling_rate = "30 min",
  from = 16, to = 32,
  ofac = 30,
  alpha = 0.0000000001,
)

export_all(raw_data = monitor_downsampled,
           processed_data = list(monitor_processed$`IND 1`),
           rythm_analysis_data = list(monitor_analysis$`IND 1`),
           ld_data = ld_data,
           new_dir_name = "IND_1")


`
![image](https://user-images.githubusercontent.com/65506362/89435947-f142d800-d71b-11ea-8726-83259ce02f65.png)
