### ISSUE TITLE
Plot Lomb_scargle function needed

### ISSUE THREAD

**Issue by giannoma** [edpclau/circadian-dynamics#17]
This would be great when looking at single individuals

**Comment by edpclau** [comment]
The 'lomb' library (it gets installed with circadian-dynamics) has such a function plot_lsp or plot.lsp . The output of lsp_mod is compatible with it. We can also build a wrapper around it and customize it. Let me know which specific things you'd like to see.

**Comment by giannoma** [comment]
Think we need a wrapper, we can disscuss why tomorrow.
