### ISSUE TITLE
multivariate rhythm analysis error 

### ISSUE THREAD

**Issue by giannoma** [edpclau/circadian-dynamics#22]
![image](https://user-images.githubusercontent.com/65670450/89918834-250c7a80-dbc0-11ea-9510-2e92e6fc7eec.png)

monitor_analysis <- multivariate_rythm_analysis(
+   monitor_processed,
+   sampling_rate = "1 hour",
+   alpha=0.000000001,
+   autocorrelation = TRUE,
+   lomb_scargle = TRUE,
+   from = 16, to = 32,
+   ofac =60)

**Comment by edpclau** [comment]
This bug should be fixed. Now whenever the autocorrelation can't find peaks, it'll return NA.
