### ISSUE TITLE
Object extport all not found

### ISSUE THREAD

**Issue by ComplejoC** [edpclau/circadian-dynamics#28]
![image](https://user-images.githubusercontent.com/44712597/92942440-8160f500-f41f-11ea-8d0f-aac758501dc1.png)
![image](https://user-images.githubusercontent.com/44712597/92942475-89209980-f41f-11ea-8329-7d40805c6a4a.png)

**Comment by edpclau** [comment]
@ComplejoC I don't understand quite well what caused the error. It could be due to the length of the dates? Could you send me the file for Monitor56 to try and trouble shoot it?

**Comment by ComplejoC** [comment]
> @ComplejoC I don't understand quite well what caused the error. It could be due to the length of the dates? Could you send me the file for Monitor56 to try and trouble shoot it?

Yes, I'll email it to you now. But it happened to all of the data when analyzed, no only this monitor.

**Comment by edpclau** [comment]
Should work now. It was an issue with an update to plot_actograms. I was eliminating the 'IND' in from of the column headers by doing str_extract(string, '\\d+'). This worked well by itself but, when we use export_all, we have a 'mean' ind. This resulted in that column not having a name. That was error. 

Now the 'mean' column will be assigned the number 999999999.
