### ISSUE TITLE
export all faceting values must have at least one value?

### ISSUE THREAD

**Issue by giannoma** [edpclau/circadian-dynamics#30]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/65670450/93724583-f1812080-fb6d-11ea-9d1c-f01c2eb7929e.png">

**Comment by edpclau** [comment]
This problem comes from the way export_all saves files, this is why it doesn't work on the server side. We need to re-do the saving process so that it works in the server.

**Comment by ComplejoC** [comment]
I'm also having this issue but on my local computer

![image](https://user-images.githubusercontent.com/44712597/94071614-3ac9ae00-fdc2-11ea-917e-8074455762af.png)
![image](https://user-images.githubusercontent.com/44712597/94071649-4ddc7e00-fdc2-11ea-827c-0746af29bd1d.png)

**Comment by edpclau** [comment]
It should be solved now. Please let me know.
