### ISSUE TITLE
export files for each variable should be separate panes

### ISSUE THREAD

**Issue by giannoma** [edpclau/circadian-dynamics#35]
[phase  Lomb scargle by window.xlsx](https://github.com/edpclau/circadian-dynamics/files/6678633/phase.Lomb.scargle.by.window.xlsx)

For a better user experience, it would be helpful if each variable output in the current rhythm analysis data file is separated into its own CSV file and rearranged for each individual as the example attached.

**Comment by edpclau** [comment]
Here's an image of how the file will look with the new format. I hope this is easier to work with.

![image](https://user-images.githubusercontent.com/65506362/124990957-0a7c9480-e00f-11eb-84b3-2a16c59d1756.png)
