### ISSUE TITLE
Autocorrelation Failing when data is 0s

### ISSUE THREAD

**Issue by giannoma** [edpclau/circadian-dynamics#6]
multivariate rhythm analysis stops when autocorrelation encounters a subject with 0s

**Comment by edpclau** [comment]
Yes, acf_by_window and lsp_by_window were not able to handle when ALL the windows had variance = 0. Now, the functions will check for this and will output a data.frame of NAs when ALL windows have variance = 0. 

**Successful Run on and IND with all 0**
![image](https://user-images.githubusercontent.com/65506362/88316381-2435a680-ccee-11ea-872c-f4e78e990065.png)
