### ISSUE TITLE
Mouse data actogram is out of phase

### ISSUE THREAD

**Issue by giannoma** [edpclau/circadian-dynamics#8]
[actogram.pdf](https://github.com/edpclau/circadian-dynamics/files/4954137/actogram.pdf)

**Comment by edpclau** [comment]
From now on, ld data must be supplied as a separate data.frame/tibble to plot_actograms. Inside, plot_actograms will left_join ld_data with the "supplied_data" using the datetime column. If the supplied data has a lower sampling rate than the ld_data, plot_actogram will only extract the ld_data which matches times on the "supplied_data" datetime column.

It's important to note that there are still some issues when the data supplied to plot_actograms is downsampled. 

Rawdata:
[actogram_rawdata.pdf](https://github.com/edpclau/circadian-dynamics/files/4956377/actogram_rawdata.pdf)

Downsampled by summing the bins:
[actogram_downsample_sum.pdf](https://github.com/edpclau/circadian-dynamics/files/4956383/actogram_downsample_sum.pdf)


Do you have any suggestion on how to solve this?

**Comment by edpclau** [comment]
The problem was with read_clocklab. The way it was reading the dates was wrong. Please check to see if the problem has been solved.

**Comment by edpclau** [comment]
Actogram Raw Data:
[actogram_raw.pdf](https://github.com/edpclau/circadian-dynamics/files/4968534/actogram_raw.pdf)

Actogram Downsampled data:
[actogram.pdf](https://github.com/edpclau/circadian-dynamics/files/4968545/actogram.pdf)


I still see the issue with the rat's movement starting before the darkness but I think that is an artifact from losing resolution when downsampling.
