### ISSUE TITLE
Error in plot actogram when data is DD

### ISSUE THREAD

**Issue by giannoma** [edpclau/circadian-dynamics#9]
![Screen Shot 2020-07-22 at 7 30 19 PM](https://user-images.githubusercontent.com/65670450/88242093-d4090680-cc51-11ea-8c14-137806b42963.png)

Error in plot_actogram(raw_data, ld_column = ld_column, export = TRUE,  : 
  unused argument (ld_column = ld_column)

**Comment by edpclau** [comment]
Solved. The error was with export_all. Internally, it was still calling the old parameter from plot_actogram.
